### ISSUE TITLE
Fully justify settings options in client

### ISSUE THREAD

**Issue by bretdavidson** [suma-project/Suma#127]

**Comment by jcraitz** [comment]
Looks like they're now left justified. Is that what you wanted @bretdavidson?

**Comment by bretdavidson** [comment]
@jcraitz I was wondering what fully justified options might look like, so option name aligned on the left side and option checkbox aligned on the right.

**Comment by jcraitz** [comment]
I'll take a look and post screenshots.

**Comment by bretdavidson** [comment]
@jcraitz I think I see what you are referring to now, it looks like the checkboxes are now to the left of the options. I believe that was a change from what I saw originally. I think that's probably fine as is then and you can ignore this issue. Thanks!
