### ISSUE TITLE
Left justify initiatives list

### ISSUE THREAD

**Issue by bretdavidson** [suma-project/Suma#128]

**Comment by bretdavidson** [comment]
@dnoneill @jcraitz @kbeswick Thoughts on this?

**Comment by jcraitz** [comment]
I've been playing with it a bit, and I think the the select being centered looks the best @bretdavidson.  Though, if you want to have it left justified, It'll be fine. do you have a preference @dnoneill?

**Comment by dnoneill** [comment]
@jcraitz Can you attach screenshots to the Trello card? That would give me a better idea.

**Comment by bretdavidson** [comment]
@jcraitz @dnoneill I don't have strong feelings either way, I was just wondering if left justification would give more space for longer initiative names

**Comment by jcraitz** [comment]
I don't like the way the longer names get cut off either.  I don't think left justifying will help too much with that.  I'll circle back to this after getting the linting stuff sorted out.

**Comment by bretdavidson** [comment]
@jcraitz @dnoneill Ok let's just close this out for now then.
