### ISSUE TITLE
No initiative should be selected by default

### ISSUE THREAD

**Issue by bretdavidson** [suma-project/Suma#132]
The feature of remembering the previously selected initiative on page refresh should be reverted to the previous behavior of requiring the user to reselect the initiative on page reload. The user should also be required to select an initiative after hitting "finish collecting". This also means the active session in the selected initiative should end on page refresh.

The concern here is the risk of entering data into the wrong initiative, especially as many initiatives use the same location tree. In many cases, a single ipad is used for multiple initiatives, and this is a safeguard to require a human check on which initiative is selected.

**Comment by bretdavidson** [comment]
- [ ] User should be required to select an initiative on page reload
- [ ] User should be required to select an initiative after hitting "finish collecting"
- [ ] Add option to settings modal to set a default initiative. This can be a dropdown list of all initiatives with a default option of "no default".
- [ ] Add helper text somewhere in display to show active initiative in addition to the dropdown menu.

**Comment by dnoneill** [comment]
@bretdavidson Are you suggesting the active initiative or the location tree name? The current behavior adds the location tree name to the title, but we got rid of that because it seemed like a backend name. We can switch that out for the initiative or we could go back to the old behavior.

**Comment by bretdavidson** [comment]
I think that both the initiative name and the location tree name should be
displayed.
