### ISSUE TITLE
LCA Transformer on PHP 7.4

### ISSUE THREAD

**Issue by herrmoody** [suma-project/Suma#143]
I just upgraded my server on which I'm running Suma and when I went to the Time Series report I got an error about no initiatives being present.

That made no sense so I looked at my Apache log and saw that there was an error about an integer being treated as an array on lines 110 and 125.  From the context that I could make out here, the variable $activity seems to be a value pulled from the array $activities, so I changed the instances of $activity['id'] here to $activity.  That seemed to fix the page.

Am I missing something here that needed to be fixed differently, or was that a bug?

**Comment by cazzerson** [comment]
I'm sorry that we didn't respond to this issue. Can you see if this is a still a problem with the latest release?

**Comment by cazzerson** [comment]
Interesting, especially since I see initiatives right below that. Do you
see any other errors in the Suma or web server logs? We haven't received
any other reports of this issue. Maybe you could also double check all of
your config files?

Thanks,
Jason

**Comment by herrmoody** [comment]
Sure.  I've looked in web server logs and haven't found anything.  So far I haven't found anything likely super-useful in troubleshooting this, but I have identified this (some of which I'm guessing that you can guess):  the error is coming back from a dataResults.php script.  If I adjust the id parameter, I can get the error to change from saying that I have no initiatives to saying that there's no data for the initiatives.  The initiative id for the initiative with the most data is 8 ("Winnetka Reference").  I'm not seeing an "8" getting passed by the form data to that script when Winnetka Reference is selected (e.g.: https://babbletron.winnetkalibrary.local/suma/analysis/reports/lib/php/dataResults.php?classifyCounts=count&days=mo,we,th,fr,sa,su,tu&edate=2022-06-28&etime=&excludeActGrps=&excludeActs=&excludeLocs=&id=1&requireActGrps=&requireActs=&sdate=2022-02-28&startHour=0000&stime=&wholeSession=no).  I am seeing an "id=1" in there and if I change "id=1" to "id=8" the returned JSON is: {"message":"No data found for that combination of filters. Please try a broader search."}

I'll check my config files and look for errors elsewhere.  The only errors I've been able to identify so far are in the web developer console (which is how I found the above URL).
