### ISSUE TITLE
Updated Install Documentation

### ISSUE THREAD

**Issue by misilot** [suma-project/Suma#154]
Hello,

I am looking to upgrade from v2 to the latest version v4? However, looking at https://suma-project.github.io/Suma/installation/ it seems like the directories have changed a bit. Just wanted to make sure I am going down the right path.

/var/www/htdocs/sumaserver/      =>  /var/www/app/suma/service/web/
/var/www/htdocs/suma/client/        =>  /var/www/app/suma/web/
/var/www/htdocs/suma/analysis/   =>  /var/www/app/suma/analysis/

[suma-repo]/analysis => /var/www/htdocs/suma/analysis/
[suma-repo]/service/web => /var/www/htdocs/sumaserver/

Now do I use [suma-repo]/web or [suma-repo]/web-sourceode/public for => /var/www/htdocs/suma/client/ ?

Are there directions on building the vue.js or angular interface?

Thanks!

**Comment by kbeswick** [comment]
Hi,

You should use [suma-repo]/web . The interfaces are built already. If you are doing any development on the new vue.js client, there are instructions here for development: https://github.com/suma-project/Suma/tree/master/web-sourcecode

Let me know if there's anything else!

**Comment by misilot** [comment]
I was able to upgrade in place for v4 from v2. I think it's working as expected but will have our users go and test.
