### ISSUE TITLE
Hours of the Week Report problem

### ISSUE THREAD

**Issue by lpmagnuson** [suma-project/Suma#68]
Hello,

I work with several institutions who use Suma, and one of our installations has a problem with the Hours of the Week report available here:

http://suma.palni.org/concordia/suma/analysis/reports/#/hourly  

Other reports available for the instance work OK, but only the results for the Hours of the Week Report don't load (just a spinny loading wheel).  I have several installations of Suma running on the same server and they aren't experiencing this problem, so I don't think it's the server environment.

 I'd love some advice in looking into this error - I'm at a bit of loss of where to start with it.

Thanks!

Lauren

**Comment by bretdavidson** [comment]
Hi Lauren,

Thanks for reaching out about Suma. Could you verify that the 'showErrors'
config option is set to false in the analysis tools config? See:
https://github.com/suma-project/Suma/blob/master/analysis/config/config_example.yaml#L4

Thanks,

Bret

**Comment by lpmagnuson** [comment]
Hi Bret,

Thanks so much, that did the trick - changing showErrors to false allowed the report to load successfully.  Awesome!

Lauren
