### ISSUE TITLE
moving site and using Nginx - session error

### ISSUE THREAD

**Issue by bennetttm** [suma-project/Suma#69]
I am moving a site from a server that was using apache, mysql and php 5.x.  Seems that a server update broke the system, and then admin login would keep coming up even after a correct password.  But I am moving all sites off that server to VMs so this was an opportune time.
The move is to Nginx, Mariadb, php-fpm, and php 7.1.

I have all http redirected to https.
I have defined sumaserver and suma as two sites, one server and one client.  The document roots are
/var/www/html/suma2/sumaserver/
and 
/var/www/html/suma2/client
won't do analytics site until these work.
If I remove sumaserver from document root the /sumaserver/ in the URL does not work.  But removing client from the document root works using /client/ although the page is not the one we created but a default client page.

the paths are symbolic links to /var/www/app/suma/service/web and /var/www/app/suma/web respectively.  I have edited the config.yaml and spaceassessConfig.js files to match the document root path.  I have edited Globals.php and BaseController.php since /sumaserver/ is not in the path because of the document root, but that didn't help but I left them edited anyway.

Using Nginx .htaccess files are not used so the rewrite rule is rewritten to the ssl.conf file.

If I go to https://sumaserver.library.appstate.edu/  I get a page that says:
 "Success!"
Please refer to the Suma documentation for more information: http://cazzerson.github.io/Suma/
By the way, that github link goes to a 404 page

I go to https://sumaserver.library.appstate.edu/admin/login I get:

500 Application error

Zend_Session_Exception: Zend_Session::start() - /var/www/app/suma/service/lib/zend/library/Zend/Session.php(Line:482): Error #2 session_start(): Failed to read session data: files (path: /var/opt/remi/php71/lib/php/session) in /var/www/app/suma/service/lib/zend/library/Zend/Session.php:495
Stack trace:
#0 /var/www/app/suma/service/lib/zend/library/Zend/Session/Namespace.php(143): Zend_Session::start(true)
#1 /var/www/app/suma/service/lib/zend/library/Zend/Auth/Storage/Session.php(86): Zend_Session_Namespace->__construct('Zend_Auth')
#2 /var/www/app/suma/service/lib/zend/library/Zend/Auth.php(91): Zend_Auth_Storage_Session->__construct()
#3 /var/www/app/suma/service/lib/zend/library/Zend/Auth.php(141): Zend_Auth->getStorage()
#4 /var/www/app/suma/service/controllers/AdminController.php(414): Zend_Auth->hasIdentity()
#5 /var/www/app/suma/service/lib/zend/library/Zend/Controller/Action.php(502): AdminController->preDispatch()
#6 /var/www/app/suma/service/lib/zend/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('loginAction')
#7 /var/www/app/suma/service/lib/zend/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /var/www/app/suma/service/web/index.php(96): Zend_Controller_Front->dispatch()
#9 {main}->getMessage()

Zend_Session_Exception: Zend_Session::start() - /var/www/app/suma/service/lib/zend/library/Zend/Session.php(Line:482): Error #2 session_start(): Failed to read session data: files (path: /var/opt/remi/php71/lib/php/session) in /var/www/app/suma/service/lib/zend/library/Zend/Session.php:495
Stack trace:
#0 /var/www/app/suma/service/lib/zend/library/Zend/Session/Namespace.php(143): Zend_Session::start(true)
#1 /var/www/app/suma/service/lib/zend/library/Zend/Auth/Storage/Session.php(86): Zend_Session_Namespace->__construct('Zend_Auth')
#2 /var/www/app/suma/service/lib/zend/library/Zend/Auth.php(91): Zend_Auth_Storage_Session->__construct()
#3 /var/www/app/suma/service/lib/zend/library/Zend/Auth.php(141): Zend_Auth->getStorage()
#4 /var/www/app/suma/service/controllers/AdminController.php(414): Zend_Auth->hasIdentity()
#5 /var/www/app/suma/service/lib/zend/library/Zend/Controller/Action.php(502): AdminController->preDispatch()
#6 /var/www/app/suma/service/lib/zend/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('loginAction')
#7 /var/www/app/suma/service/lib/zend/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /var/www/app/suma/service/web/index.php(96): Zend_Controller_Front->dispatch()
#9 {main}->getTraceAsString()

I suspect it may be a path issue maybe with where to write the session data.  PHP71 from the Remi Repository is installed in /var/opt/remi/php71 path.

I've checked that path and there are not files in the session directory to read and there is no error about not being able to write the files.    My server is in a vlan not accessible from off campus, sorry.

My Nginx ssl.conf file is below if anyone wants to try it.

Any help would be appreciated,

Thomas Bennett
Systems & Operations Analyst
Appalachian State University Library

ssl.conf (nginx.conf uses an include for the directory that ssl.conf is in):
# SUMASERVER

    server {
        listen       443 ssl http2 ;
        server_name  sumaserver.library.appstate.edu;
        root         /var/www/html/suma2/sumaserver/;
        access_log      /var/log/nginx/sumaserver_access.log;
        error_log       /var/log/nginx/sumaserver_error.log debug;
        # rewrite logs to error log at notice or higher
        rewrite_log on;

        ssl_certificate "/etc/pki/tls/certs/star.library.appstate.edu.pem";
        ssl_certificate_key "/etc/pki/tls/private/star.library.appstate.edu.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/pki/tls/certs/dh2048.pem;

        index   index.html index.php;

        location / {
                autoindex on;
                disable_symlinks off;
		# Literal translation of .htaccess file
		# see http://www.anilcetin.com/convert-apache-htaccess-to-nginx/
                if (-e $request_filename){
                        set $rule_0 1;
                }
                if ($request_filename ~ "-l"){
                        set $rule_0 1;
                }
                if (-d $request_filename){
                        set $rule_0 1;
                }
                if ($rule_0 = "1"){

                #ignored: "-" thing used or unknown variable in regex/rew
                }
                rewrite ^/.*$ /index.php last;

        }

        location = /favicon.ico {
                log_not_found off;
                access_log off;
        }

        location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
        }

        # PHP-FPM PARAMETERS
        #NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php-fpm.sock;
                fastcgi_param SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                fastcgi_param SCRIPT_NAME $fastcgi_script_name;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_intercept_errors on;
                fastcgi_read_timeout    256s;
        }
    }

# SUMA Client
    server {
        listen       443 ssl http2 ;
        server_name  suma.library.appstate.edu;
        root         /var/www/html/suma2/client/;
        access_log      /var/log/nginx/suma_access.log;
        error_log       /var/log/nginx/suma_error.log;
        # rewrite logs to error_log at notice or higher
        rewrite_log on;

        ssl_certificate "/etc/pki/tls/certs/star.library.appstate.edu.pem";
        ssl_certificate_key "/etc/pki/tls/private/star.library.appstate.edu.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/pki/tls/certs/dh2048.pem;

        index   index.html index.php;

        location / {
		# should turn off autoindex in production
                autoindex on;
                disable_symlinks off;
        }

	# Don’t log missing ico file
        location = /favicon.ico {
                log_not_found off;
                access_log off;
        }

        location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
        }

        # PHP-FPM PARAMETERS
        # pass the PHP scripts to FastCGI server listening on socket
        #NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param SCRIPT_NAME $fastcgi_script_name;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_intercept_errors on;
                fastcgi_read_timeout    256s;
        }

	# Don’t log missing image files in web log
       location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
               expires max;
               log_not_found off;
       }

        autoindex      on;
    }

**Comment by bennetttm** [comment]
/var/opt/remi/php71/lib/php/session was owned by root:apache.  I changed that to root:nginx and now get a login page.  YEAH! ;-)  Now to see if I can log in.  I'm still not getting the correct client page, looks like a default page.

**Comment by bennetttm** [comment]
Logged in as admin but the page is a list of tables each giving a similar error for Global.php and BaseController.php.  Had to return to the original version of those files ;-).

**Comment by bennetttm** [comment]
Under Suma Administrative Tools, the drop down appears to be populating but clicking on Display doesn't show anything.

Client still does bring up the page we should have, still looks like a default page and there doesn't seem to be any errors logging to indicate why.  Nothing under select an initiative  dropdown.

**Comment by bretdavidson** [comment]
Hi Thomas,

I'm not terribly familiar with Nginx, but this sounds like an issue with
rewrite rules. Maybe something like this will help?

https://www.nginx.com/blog/converting-apache-to-nginx-rewrite-rules/

Bret

**Comment by bennetttm** [comment]
Thanks  for the suggestion, thats actually one of the first URLs I found for translating rewrite rules.  At the bottom of that post is almost the apache rewrite rules suma uses but no one replied to that guy on line on how to rewrite it.  The best I found was the converter at http://www.anilcetin.com/convert-apache-htaccess-to-nginx/ which gave me the one I used but I still don't understand why it doesn't work when I set document root to where it should be and /sumaserver/ does not follow the symlink even though I turned disable symlinks off.  I am going to look again at the if rules in the rewrite and to see exactly what they mean, could be I just assume they were the same as the .htaccess rules.

Thanks again
Thomas

**Comment by bennetttm** [comment]
Well, I have installed apache but still using PHP71.  I had to rename the session.yaml so it would not be used so I could get admin logged in.  I don't know if something has changed in the call to start session except that it seems now start session can accept parameters to override php.ini settings.
