### ISSUE TITLE
Data Collection Client Access

### ISSUE THREAD

**Issue by jonahlyn** [suma-project/Suma#72]
Hello,

We are implementing an installation of Suma and have a question about the security of the Data Collection Client. It seems as though anyone can startup a new session and start collecting data if they know the right URL to go to. I'm not sure if this is a problem beyond possibly skewing the reported data. Is this something that we should be concerned about? Did anyone else do anything to secure their data collection client or have any recommendations about how it could be done?

Thanks.
Jonahlyn

**Comment by misilot** [comment]
Hi @jonahlyn did you happen to do address this? We are looking at doing the same, however we are looking at putting it behind Shibboleth to address this for our uses.
