### ISSUE TITLE
Administration tools bring back to login page

### ISSUE THREAD

**Issue by Hugostg1976** [suma-project/Suma#78]
Hi,

I am trying to install Suma for a couple of days on a CentOS 7 LAMP server now but I can't seem to be able to have it to work. I am now able to connect to the Sumaserver login page but when I click the configuration links, it brings me back to the login page. 

I am now trying to enable the sumaserver debug log. I did set the SUMA_DEBUG to true in the /var/www/html/sumaserver/config/config.yaml. 

### # Path Configuration
SUMA_SERVER_PATH: /var/www/app/sumaserver
SUMA_CONTROLLER_PATH: /var/www/app/sumaserver/controllers
SUMA_BASE_URL: /sumaserver

# Debug mode
SUMA_DEBUG: true

I configured the sumaserver debug log in the /var/www/app/sumaserver/config/config.yaml.

production:
    sumaserver:
        db:
            host: localhost
            platform: Pdo_Mysql
            dbname: suma_prod
            user: suma_admin
            pword: irewatl!
            port: 3306
        log:
            path: /var/www/html/suma/log
            name: sumaserver.log

I followed the Troubleshooting part Suma on SELinux and made sure the log was writtable by Apache. 

Folder : drwxrwxr-x. 2 root apache 28 Apr 25 15:15 log
File : -rwxrwxr-x. 1 root apache 55 Apr 26 11:15 sumaserver.log

Following another Github issue resolved, I made sure my PHP PDO modules were installed but here is a list of all the PHP modules installed. 

[root@suma log]# yum list installed | grep php
php.x86_64                              5.4.16-43.el7_4.1              @updates
php-ZendFramework.noarch                1.12.20-1.el7                  @epel
php-ZendFramework-Db-Adapter-Mysqli.noarch
php-ZendFramework-Db-Adapter-Pdo.noarch 1.12.20-1.el7                  @epel
php-ZendFramework-Db-Adapter-Pdo-Mysql.noarch
php-bcmath.x86_64                       5.4.16-43.el7_4.1              @updates
php-cli.x86_64                          5.4.16-43.el7_4.1              @updates
php-common.x86_64                       5.4.16-43.el7_4.1              @updates
php-fedora-autoloader.noarch            1.0.0-1.el7                    @epel
php-gd.x86_64                           5.4.16-43.el7_4.1              @updates
php-mbstring.x86_64                     5.4.16-43.el7_4.1              @updates
php-mysql.x86_64                        5.4.16-43.el7_4.1              @updates
**php-pdo.x86_64                          5.4.16-43.el7_4.1              @updates**
php-php-gettext.noarch                  1.0.12-1.el7                   @epel
php-process.x86_64                      5.4.16-43.el7_4.1              @updates
php-tcpdf.noarch                        6.2.13-1.el7                   @epel
php-tcpdf-dejavu-sans-fonts.noarch      6.2.13-1.el7                   @epel
php-tidy.x86_64                         5.4.16-7.el7                   @epel
php-xml.x86_64                          5.4.16-43.el7_4.1              @updates
phpMyAdmin.noarch                       4.4.15.10-2.el7                @epel

I made sure that the PDO modules were loaded in PHP. 

Could someone help me figure it out please?

Regards,

Hugo St-Gelais
Analyste des systèmes | Systems analyst
Réseau de bibliothèques | Library network
Université d'Ottawa | University of Ottawa

**Comment by bretdavidson** [comment]
Hi Hugo,

Thanks for reaching out about Suma. Did you create a copy of the `session_example.yaml` file in `/services/config`? If so, can you try Suma without that file first? Or could you verify the path value that you are setting in that file (again, if you created it during installation)?

Thanks,

Bret

From the installation docs:

This is an optional file to increase session security and allow the specification of custom session properties.

In the /SUMA_SERVER_INSTALL_DIR/services/config/ directory, copy session_example.yaml to a new file session.yaml. SUMA_BASE_URL must be set to the URL path for the Suma server. For example, if the URL is http://YOUR_HOST/sumaserver, set this to /sumaserver.

**Comment by Hugostg1976** [comment]
It worked. 

Thank you for your quick reply.

**Comment by bretdavidson** [comment]
Great! Let me know if you have any other questions, thanks for your interest in Suma.
