### ISSUE TITLE
Hourly Reports Error - Undefined index starthour

### ISSUE THREAD

**Issue by lpmagnuson** [suma-project/Suma#81]
Hi, we've found an error when attempting to load the Hours of the Week report - the report spins forever resulting eventually in this message:

Notice!
There was a problem generating the report. Please try again or contact your system administrator.
Error Code: 0
Error Message: Data.getData Timeout

Logs show:

[Mon Dec 17 11:33:28 2018] [warn] [client 68.94.113.235] mod_fcgid: stderr: PHP Notice:  Undefined index: startHour in /home/plnsuma/inst/Suma/analysis/reports/lib/php/Data.php on line 396, referer: http://suma.something.org/inst/analysis/reports/

Other reports seem to running OK.  Any pointers to help troubleshoot this are appreciated!

Lauren

**Comment by bretdavidson** [comment]
Hi Lauren,

Hope you were able to diagnose this issue. Going to close this for now, but please reopen if needed.

bret
