### ISSUE TITLE
Suma app can't find javascript

### ISSUE THREAD

**Issue by tdouty** [suma-project/Suma#82]
I'm trying to install Suma to a Ubuntu server and it is working except that it can't find the javascript. 
    
I tried to follow the directions, modifying them to our installation directory.

We used the soft link method so if we put a new version in later, we can just change the soft links and all should be good.

Our page may be firewalled so you probably can't see it, but I haven't checked it to see if it's open.

So, I can bring up the server page and get a success message at https://spaceassessment.libraries.psu.edu/sumaserver/.

I can do an admin login and can get to the Suma Administrative Tools" window. When we get to the location tree editor at https://spaceassessment.libraries.psu.edu/sumaserver/admin/locations, the javascript doesn't load. The path is off by one directory level.  For instance,
GET https://spaceassessment.libraries.psu.edu/sumaserver/js/lo-dash/lodash.compat.min.js net::ERR_ABORTED 404 (Not Found)
    
If wI remove the /sumaserver before the /js, it works (ie https://spaceassessment.libraries.psu.edu/js/lo-dash/lodash.compat.min.js)

So apparently there is a problem with a config somewhere, but I am not sure what isn't right. In the code where it is trying to load the javascript, I modified the php code and dumped out the base directory and it is /sumaserver. 

Any help you can offer would be greatly appreciated.

Here are the some config files below.  Instead of putting the website at /var/www/html, I have it at /data/websites/spaceassessment.  Suma 3.0 is installed at /data/suma-install/Suma-3.0.0 and the links are then as follows:

root@L5spaceassessment:/data/websites/spaceassessment# ls -al /data/websites/spaceassessment/
total 20
drwxr-xr-x 4 root     root     4096 Jul  2 12:55 .
drwxr-xr-x 3 root     root     4096 Jun 25 15:55 ..
-rw-r--r-- 1 root     root      238 Jun 26 16:48 hello.html
drwxr-xr-x 3 www-data www-data 4096 Jul  2 12:57 logs
drwxr-xr-x 2 root     root     4096 Jun 27 11:38 suma
lrwxrwxrwx 1 root     root       42 Jun 27 09:56 sumaserver -> /data/suma-install/Suma-3.0.0/service/web/

root@L5spaceassessment:/data/websites/spaceassessment# ls -al /data/websites/spaceassessment/suma
total 8
drwxr-xr-x 2 root root 4096 Jun 27 11:38 .
drwxr-xr-x 4 root root 4096 Jul  2 12:55 ..
lrwxrwxrwx 1 root root   38 Jun 27 10:01 analysis -> /data/suma-install/Suma-3.0.0/analysis
lrwxrwxrwx 1 root root   33 Jun 27 10:01 client -> /data/suma-install/Suma-3.0.0/web
lrwxrwxrwx 1 root root   37 Jun 27 11:38 service -> /data/suma-install/Suma-3.0.0/service

Apache config: I tried changing the https redirect to have /sumaserver on the end and that didn't change anything.
<VirtualHost *:80>

    DocumentRoot /data/websites/spaceassessment/sumaserver
    ServerName spaceassessment.libraries.psu.edu
    ErrorLog ${APACHE_LOG_DIR}/spaceassessment_error_log
    CustomLog ${APACHE_LOG_DIR}/spaceassessment_access_log common
    <Directory  /data/websites/spaceassessment/sumaserver>
     AllowOverride All
    </Directory>

     Redirect permanent / https://spaceassessment.libraries.psu.edu
#    RewriteEngine on
#    RewriteCond %{SERVER_PORT} =80
#    RewriteRule ^(.*) https://%{SERVER_NAME}%{REQUEST_URI} [R,L]

</VirtualHost>

<VirtualHost *:443>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot /data/websites/spaceassessment/sumaserver
    ServerName spaceassessment.libraries.psu.edu
    ErrorLog ${APACHE_LOG_DIR}/spaceassessment_ssl_error_log
    CustomLog ${APACHE_LOG_DIR}/spaceassessment_ssl_access_log common
    <Directory /data/websites/spaceassessment/sumaserver >
     RewriteEngine On
     RewriteCond %{REQUEST_FILENAME} -s [OR]
     RewriteCond %{REQUEST_FILENAME} -l [OR]
     RewriteCond %{REQUEST_FILENAME} -d
     RewriteRule ^.*$ - [NC,L]
     RewriteRule ^.*$ index.php [NC,L]     AllowOverride All
     Require all granted
     Options FollowSymLinks
    </Directory>

 ssl cert info .....

</VirtualHost>

root@L5spaceassessment:/data/websites/spaceassessment# cat /data/suma-install/Suma-3.0.0/analysis/config/config.yaml
# Copy this file to a new file `config.yaml`

# Display errors. Valid values are true or false.
showErrors: false

# Change baseUrl to the URL for your Suma Query Server. If you
# used a directory other than `sumaserver` in the "Suma Software Installation"
# section in `INSTALL.md`, that should be reflected in this URL.
serverIO:
        baseUrl: https://spaceassessment.libraries.psu.edu/sumaserver/query

# Change analysisBaseUrl to the URL for your analysis tools
analysisBaseUrl: http://spaceassessment.libraries.psu.edu/suma/analysis/reports

# Configuration for nightly report
# Default Timezone. See: http://php.net/manual/en/timezones.php
# Date display format. See: http://php.net/manual/en/function.date.php
# Recipient e-mail addresses separated by commas
# Error recipient e-mail addresses separated by commas
# emailFrom (optional). Single address
# emailSubj (optional). Customize text for email subject
nightly:
    timezone: America/New_York
    displayFormat: m-d-Y
    recipients: ul-itech-sys-apps@lists.psu.edu
    errorRecipients: ul-itech-sysapps@lists.psu.edu
    emailFrom: "Suma Reports <ul-itech-sysapps@lists.psu.edu>"
    emailSubj: "Suma Nightly Report:"

root@L5spaceassessment:/data/websites/spaceassessment# cat /data/suma-install/Suma-3.0.0/service/config/config.yaml
# Copy this file to a new file `config.yaml`.
#
# You must modify the following:
#
#    production:
#        sumaserver:
#            db:
#                host: host location of your mysql database
#                dbname: suma mysql database name
#                user: suma mysql **application** account name
#                pword: suma mysql **application** account password
#                port: mysql port number
#            log:
#                path: path to log directory
#                name: sumaserver.log
#
#  * Be sure that the log directory specified in `sumaserver:log:path`
#  both exists and is **writable by the web server**.

production:
    sumaserver:
        db:
            host: localhost
            platform: Pdo_Mysql
            dbname: xxxxxxx
            user: xxxxxxxx
            pword: xxxxxxxx
            port: xxxxxx
        log:
            path: /data/websites/spaceassessment/logs/sumaserver
            name: sumaserver_prod.log
        admin:
            user: xxxxxxxxx
            pass: xxxxxxxx
    queryserver:
        db:
            limit: 10000

development:
    _extends: production
    sumaserver:
        db:
            dbname: xxxxxxxx
            user: xxxxxxxx
            pword: xxxxxxxxx
        log:
            path: /data/websites/spaceassessment/logs/sumaserver
            name: sumaserver_test.log
        admin:
            user: xxxxxxxxxx
            pass: xxxxxxxxxx

root@L5spaceassessment:/data/websites/spaceassessment# cat /data/suma-install/Suma-3.0.0/service/web/config/config.yaml
# Copy this file a new file `config.yaml`.
#
# `SUMA_SERVER_PATH` must be set to the `SUMA_SERVER_INSTALL_DIR`
#  where the Suma server was installed earlier (e.g. `/var/www/app/sumaserver`).
#
# `SUMA_CONTROLLER_PATH` must be set to `SUMA_SERVER_INSTALL_DIR/controllers`
#  (e.g. `/var/www/app/sumaserver/controllers`).
#
# `SUMA_BASE_URL` must be set to the URL path for the Suma server.
#  For example, if the URL is `http://YOUR_HOST/sumaserver`, set this to `/sumaserver`.
#
# `SUMA_DEBUG` can be set to `true` if you would like
#  to see more verbose error messages. This should generally be set to `false`.

# Path Configuration
SUMA_SERVER_PATH: /data/websites/spaceassessment/suma/service
SUMA_CONTROLLER_PATH: /data/websites/spaceassessment/suma/service/controllers
SUMA_BASE_URL: /sumaserver

# Debug mode
SUMA_DEBUG: true

**Comment by kbeswick** [comment]
Hi Todd, 

One thing that jumps out at me is that your DocumentRoot in your Apache config is defined to "/data/websites/spaceassessment/sumaserver". This would explain why you are seeing the 404 problem with JS being one directory level off - the DocumentRoot should be "/data/websites/spaceassessment". 

The other thing that I notice is in your "/data/suma-install/Suma-3.0.0/service/web/config/config.yaml" file, your SUMA_SERVER_PATH should be "/data/websites/spaceassessment/sumaserver" and your SUMA_CONTROLLER_PATH should be "/data/websites/spaceassessment/sumaserver/controllers" based on the directory structure you showed above.

Let me know if this helps at all.

**Comment by tdouty** [comment]
Doing that, I can display a hello world file that is in the document root at /data/websites/spaceassessment. (https://spaceassessment.libraries.psu.edu/hello.html)

However, the url https://spaceassessment.libraries.psu.edu/sumaserver/ gives me this error:

Warning: include_once(Zend/Loader.php): failed to open stream: No such file or directory in /data/suma-install/Suma-3.0.0/service/web/index.php on line 46

Warning: include_once(): Failed opening 'Zend/Loader.php' for inclusion (include_path='.:/usr/share/php:/data/websites/spaceassessment/sumaserver:/data/websites/spaceassessment/sumaserver/lib/zend/library') in /data/suma-install/Suma-3.0.0/service/web/index.php on line 46
Trouble loading Suma server application. This is often caused by configuration issues. Please refer to the troubleshooting docs at http://suma-project.github.io/Suma The raw output is below: Possible error in SUMA_SERVER_PATH.


Todd Douty <todd.douty@psu.edu>

Systems Administrator

The Pennsylvania State University Libraries

(814) 865-4850

________________________________

**Comment by kbeswick** [comment]
My bad, the SUMA_SERVER_PATH should be "/data/suma-install/Suma-3.0.0/service" and SUMA_CONTROLLER_PATH should be "/data/suma-install/Suma-3.0.0/service/controllers". Let me know if this fixes that error.

**Comment by tdouty** [comment]
So that file was ok as it was then if I'm suing the softlinks. I put it back to the way it was prior to the change:

root@L5spaceassessment:~# cat /data/suma-install/Suma-3.0.0/service/web/config/config.yaml
# Copy this file a new file `config.yaml`.
#
# `SUMA_SERVER_PATH` must be set to the `SUMA_SERVER_INSTALL_DIR`
#  where the Suma server was installed earlier (e.g. `/var/www/app/sumaserver`).
#
# `SUMA_CONTROLLER_PATH` must be set to `SUMA_SERVER_INSTALL_DIR/controllers`
#  (e.g. `/var/www/app/sumaserver/controllers`).
#
# `SUMA_BASE_URL` must be set to the URL path for the Suma server.
#  For example, if the URL is `http://YOUR_HOST/sumaserver`, set this to `/sumaserver`.
#
# `SUMA_DEBUG` can be set to `true` if you would like
#  to see more verbose error messages. This should generally be set to `false`.

# Path Configuration
SUMA_SERVER_PATH: /data/websites/spaceassessment/suma/service
SUMA_CONTROLLER_PATH: /data/websites/spaceassessment/suma/service/controllers
SUMA_BASE_URL: /sumaserver

# Debug mode
SUMA_DEBUG: true





The sumaserver now responds with ok at https://spaceassessment.libraries.psu.edu/sumaserver/.




Now on to the admin login:

https://spaceassessment.libraries.psu.edu/sumaserver/admin

I get a page not found.

Not Found

The requested URL /index.php was not found on this server.



Todd Douty <todd.douty@psu.edu>

Systems Administrator

The Pennsylvania State University Libraries

(814) 865-4850

________________________________

**Comment by kbeswick** [comment]
The "/data/websites/spaceassessment/suma/service" symlink should be removed, and your config should be updated to the last paths I provided. The reason for this is that with that link in place, you are likely exposing config files that include database credentials through Apache.

There is a chance this could fix the other issue too - can you make this update and let me know if you still get the same error?

**Comment by tdouty** [comment]
I removed the "/data/websites/spaceassessment/suma/service" symlink and changed /data/suma-install/Suma-3.0.0/service/web/config/config.yaml as follows:

# Copy this file a new file `config.yaml`.
#
# `SUMA_SERVER_PATH` must be set to the `SUMA_SERVER_INSTALL_DIR`
#  where the Suma server was installed earlier (e.g. `/var/www/app/sumaserver`).
#
# `SUMA_CONTROLLER_PATH` must be set to `SUMA_SERVER_INSTALL_DIR/controllers`
#  (e.g. `/var/www/app/sumaserver/controllers`).
#
# `SUMA_BASE_URL` must be set to the URL path for the Suma server.
#  For example, if the URL is `http://YOUR_HOST/sumaserver`, set this to `/sumaserver`.
#
# `SUMA_DEBUG` can be set to `true` if you would like
#  to see more verbose error messages. This should generally be set to `false`.

# Path Configuration
SUMA_SERVER_PATH: /data/suma-install/Suma-3.0.0/service
SUMA_CONTROLLER_PATH: /data/suma-install/Suma-3.0.0/service/controllers
SUMA_BASE_URL: /sumaserver

# Debug mode
SUMA_DEBUG: true


https://spaceassessment.libraries.psu.edu/sumaserver/admin is still giving me a not found error.



Todd Douty <todd.douty@psu.edu>

Systems Administrator

The Pennsylvania State University Libraries

(814) 865-4850

________________________________

**Comment by kbeswick** [comment]
I'm not sure if this is a typo / transcription error, but in your Apache config that you list in the original message, within the "<Directory /data/websites/spaceassessment/sumaserver >" block, there is a line that has two statements on the same line: 

 RewriteRule ^.*$ index.php [NC,L]     AllowOverride All

Is this like this in the actual config file? If so, it might be causing issues.

**Comment by tdouty** [comment]
Good eye and yes it was like that in the config. I changed it and restarted apache, but it still gives me the not found error.

If it helps, here is what I see looking at the sumaserver folder. I don't see anything by the name of admin, which is what the path in the url would lead to or am I missing something on how it works.

root@L5spaceassessment:~# ls -l /data/websites/spaceassessment/sumaserver
lrwxrwxrwx 1 root root 42 Jun 27 09:56 /data/websites/spaceassessment/sumaserver -> /data/suma-install/Suma-3.0.0/service/web/
root@L5spaceassessment:~# ls -l /data/websites/spaceassessment/sumaserver/
total 32
drwxrwxr-x 2 root root 4096 Jul 12 11:40 config
drwxrwxr-x 3 root root 4096 Jul 31  2018 css
-rw-r--r-- 1 root root  248 Jul  5 10:06 hello.html
-rw-rw-r-- 1 root root  191 Jul 31  2018 htaccess_example
-rw-rw-r-- 1 root root 3105 Jul 31  2018 index.php
drwxrwxr-x 7 root root 4096 Jul 31  2018 js
drwxrwxr-x 3 root root 4096 Jul 31  2018 lib
-rw-rw-r-- 1 root root   43 Jul 31  2018 README




Todd Douty <todd.douty@psu.edu>

Systems Administrator

The Pennsylvania State University Libraries

(814) 865-4850

________________________________

**Comment by kbeswick** [comment]
Hmm. Is mod_rewrite enabled in Apache? Running "sudo a2enmod rewrite" should enable or tell you that it is enabled.

**Comment by tdouty** [comment]
It must be because the rewrite to https happens. Ill  double check Monday.
________________________________

**Comment by kbeswick** [comment]
You are using a Redirect for https according to your Apache config, which is part of mod_alias. I would have expected there to be an error thrown if you had Rewrite directives in your Apache config without the mod_rewrite enabled, but the problem you're seeing seems related to the rewrite rules not working correctly, so figured I'd double check that it is definitely enabled.

**Comment by tdouty** [comment]
Monday and back to work .... Yes, mod-rewrite is already enabled.

root@L5spaceassessment:~# a2enmod rewrite
Module rewrite already enabled



Todd Douty <todd.douty@psu.edu>

Systems Administrator

The Pennsylvania State University Libraries

(814) 865-4850

________________________________

**Comment by queryluke** [comment]
@tdouty 

I've tried to set up a fresh server as best I can to replicate your path's and environment. From reading the thread, I think you've got everything below in place, but I just want to confirm:


### /data/suma-install/Suma-3.0.0/
```
[root@suma Suma-3.0.0]# pwd
/data/suma-install/Suma-3.0.0
[root@suma Suma-3.0.0]# ls -al
total 52
drwxr-xr-x. 7 root root 4096 Jul 15 12:09 .
drwxr-xr-x. 3 root root 4096 Jul 15 12:09 ..
drwxr-xr-x. 6 root root 4096 Jul 15 12:09 analysis
drwxr-xr-x. 5 root root 4096 Jul 15 12:09 docs
-rw-r--r--. 1 root root  460 Jul 15 12:09 .editorconfig
drwxr-xr-x. 8 root root 4096 Jul 15 12:09 .git
-rw-r--r--. 1 root root  385 Jul 15 12:09 .gitignore
-rw-r--r--. 1 root root    0 Jul 15 12:09 .gitmodules
-rw-r--r--. 1 root root  708 Jul 15 12:09 .jshintrc
-rw-r--r--. 1 root root 1079 Jul 15 12:09 LICENSE
-rw-r--r--. 1 root root 3662 Jul 15 12:09 README.md
drwxr-xr-x. 9 root root 4096 Jul 15 12:09 service
-rw-r--r--. 1 root root  646 Jul 15 12:09 .travis.yml
drwxr-xr-x. 5 root root 4096 Jul 15 12:09 web
```

### /data/websites/spacesassessment
```
[root@suma spaceassessment]# pwd
/data/websites/spaceassessment
[root@suma spaceassessment]# ls -al
total 16
drwxr-xr-x. 3 root root 4096 Jul 15 12:28 .
drwxr-xr-x. 3 root root 4096 Jul 15 12:11 ..
-rw-r--r--. 1 root root   56 Jul 15 12:30 index.html
drwxr-xr-x. 2 root root 4096 Jul 15 12:14 suma
lrwxrwxrwx. 1 root root   41 Jul 15 12:12 sumaserver -> /data/suma-install/Suma-3.0.0/service/web
```

### /data/suma-install/Suma-3.0.0/service/web/config/config.yaml
```
# Path Configuration
SUMA_SERVER_PATH: /data/suma-install/Suma-3.0.0/service
SUMA_CONTROLLER_PATH: /data/suma-install/Suma-3.0.0/service/controllers
SUMA_BASE_URL: /sumaserver

# Debug mode
SUMA_DEBUG: true
```

### Apache config
This one might be a little different, but this is what I would consider the _minimum_ config. Also, it's a bit different from the install example. I've had better luck by keeping the rewrite rules separate from the rest of the DocumentRoot, but this _shouldn't_ be the issue.
```
DirectoryIndex index.php index.html


<VirtualHost *:80>
  ServerName suma.localhost
  DocumentRoot "/data/websites/spaceassessment"

  <Directory "/data/websites/spaceassessment">
    AllowOverride All
    Options -Indexes +FollowSymLinks
  </Directory>

  <Directory "/data/websites/spaceassessment/sumaserver">
    Require all granted
    RewriteEngine on
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]
    RewriteRule ^.*$ index.php [NC,L]
  </Directory>
</VirtualHost>
```

If that doesn't change anything, you say the admin error is giving a "not found error". Is this the standard apache 404, or is it a php error?

**Comment by tdouty** [comment]
I don't have an index.html in /data/websites/spaceassessment and I found a few difference in the apache config so change it so that it now looks like this:

root@L5spaceassessment:~# cat /etc/apache2/sites-enabled/spaceassessment.conf
<VirtualHost *:80>

    DocumentRoot /data/websites/spaceassessment
    ServerName spaceassessment.libraries.psu.edu
    ErrorLog ${APACHE_LOG_DIR}/spaceassessment_error_log
    CustomLog ${APACHE_LOG_DIR}/spaceassessment_access_log common
    <Directory "/data/websites/spaceassessment">
      AllowOverride All
      Options -Indexes +FollowSymLinks
    </Directory>

    <Directory "/data/websites/spaceassessment/sumaserver">
      Require all granted
      RewriteEngine on
      RewriteCond %{REQUEST_FILENAME} -s [OR]
      RewriteCond %{REQUEST_FILENAME} -l [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^.*$ - [NC,L]
      RewriteRule ^.*$ index.php [NC,L]
    </Directory>

     Redirect permanent / https://spaceassessment.libraries.psu.edu
#    RewriteEngine on
#    RewriteCond %{SERVER_PORT} =80
#    RewriteRule ^(.*) https://%{SERVER_NAME}%{REQUEST_URI} [R,L]
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot /data/websites/spaceassessment
    ServerName spaceassessment.libraries.psu.edu
    ErrorLog ${APACHE_LOG_DIR}/spaceassessment_ssl_error_log
    CustomLog ${APACHE_LOG_DIR}/spaceassessment_ssl_access_log common
    <Directory "/data/websites/spaceassessment">
      AllowOverride All
      Options -Indexes +FollowSymLinks
    </Directory>

    <Directory "/data/websites/spaceassessment/sumaserver">
      Require all granted
      RewriteEngine on
      RewriteCond %{REQUEST_FILENAME} -s [OR]
      RewriteCond %{REQUEST_FILENAME} -l [OR]
      RewriteCond %{REQUEST_FILENAME} -d
      RewriteRule ^.*$ - [NC,L]
      RewriteRule ^.*$ index.php [NC,L]
    </Directory>

     SSLEngine on
     SSLProtocol all -SSLv2 -SSLv3
     #SSLCipherSuite ALL:!ADH:!EXPORT:!SSLv2:RC4+RSA:+HIGH:+MEDIUM:+LOW
     SSLCipherSuite ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS:!3DES
     SSLCertificateFile /etc/apache2/ssl-certs/spaceassessment.libraries.psu.edu.crt
     SSLCertificateKeyFile /etc/apache2/ssl-certs/private/spaceassessment.libraries.psu.edu.key
     SSLCertificateChainFile /etc/apache2/ssl-certs/SHA256CHAIN.pem
</VirtualHost>



Still get an error trying to find the javascript. The attachment shows what is displayed in the developers console in Chrome.

If I try to browse to the url in the developers console (https://spaceassessment.libraries.psu.edu/sumaserver/admin/sumaserver/js/views/admin/locations.js) I get:

404 Not found

Zend_Controller_Action_Exception: Action "sumaserver" does not exist and was not trapped in __call() in /data/suma-install/Suma-3.0.0/service/lib/zend/library/Zend/Controller/Action.php:485
Stack trace:
#0 /data/suma-install/Suma-3.0.0/service/lib/zend/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('sumaserverActio...', Array)
#1 /data/suma-install/Suma-3.0.0/service/lib/zend/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('sumaserverActio...')
#2 /data/suma-install/Suma-3.0.0/service/lib/zend/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /data/suma-install/Suma-3.0.0/service/web/index.php(93): Zend_Controller_Front->dispatch()
#4 {main}->getMessage()

Zend_Controller_Action_Exception: Action "sumaserver" does not exist and was not trapped in __call() in /data/suma-install/Suma-3.0.0/service/lib/zend/library/Zend/Controller/Action.php:485
Stack trace:
#0 /data/suma-install/Suma-3.0.0/service/lib/zend/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('sumaserverActio...', Array)
#1 /data/suma-install/Suma-3.0.0/service/lib/zend/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('sumaserverActio...')
#2 /data/suma-install/Suma-3.0.0/service/lib/zend/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /data/suma-install/Suma-3.0.0/service/web/index.php(93): Zend_Controller_Front->dispatch()
#4 {main}->getTraceAsString()






Todd Douty <todd.douty@psu.edu>

Systems Administrator

The Pennsylvania State University Libraries

(814) 865-4850

________________________________

**Comment by queryluke** [comment]
Ok, are any of the scripts on that page loading or are you only getting a 404 for the locations.js?

For example, on the following page can you open Chrome's dev tools and click on the network tab, then reload the page.
https://spaceassessment.libraries.psu.edu/sumaserver/admin/locations

There should be 2 css files and 6 javascript files (2 from google apis).
(suma files)
- jquery-ui-1.10.3.custom.min.css
- admin.css
- nestedSortable.js
- jquery.history.js
- lodash.compat.min.js
- locations.js

(google api)
- jquery.min.js
- jquery-ui.min.js


Also, I looked at our production instance's Apache configs, and the only slight difference I can see is that our Redirect permanent has a trailing slash (I'll not very sysadmin-y, so I have no clue if this might help)

```
Redirect permanent / https://suma-prod01.lib.ncsu.edu/
```

**Comment by tdouty** [comment]
I'm out of the office today thru the 24th. I'll get back to this then. Thanks for all the help. I'm sure we'll get to the bottom of it. Maybe we could do a zoom session and I can let you control the SSH session and look around.


Todd Douty <todd.douty@psu.edu>

Systems Administrator

The Pennsylvania State University Libraries

(814) 865-4850

________________________________
