### ISSUE TITLE
wrong times recorded for sessions / transactions

### ISSUE THREAD

**Issue by kenirwin** [suma-project/Suma#83]
We noticed recently that our nightly reports are reporting transactions while the library is closed. Upon closer inspection, we find that transactions are being recorded as though they occur four hours later than is correct -- as we are in EDT, that is corresponds to GMT/UTC. It appears to have started doing this in the last half of June. 

I've checked what time the server thinks it is using the linux `date` command, and it shoes the correct time including in this format:  `Wed Jul 24 08:54:46 EDT 2019`

When I check the `transaction` table, an entry from 8:54 this morning shows the time:
2019-07-24 12:54:46 

Is there a setting I need to change somewhere?

The only relevant setting I see is this one:
**service/analysis/config/config.yaml:**
timezone: America/New_York

**Comment by cazzerson** [comment]
Hi Ken,

You may want to check to see that the correct timezone is set in php.ini:

https://www.php.net/manual/en/datetime.configuration.php#ini.date.timezone

Thanks,
Jason

**Comment by kenirwin** [comment]
Thanks Jason – that was the answer.

Ken
