### ISSUE TITLE
How do I format JSON for an import in admin tools?

### ISSUE THREAD

**Issue by emlanctot** [suma-project/Suma#85]
I've looked at this: https://github.com/suma-project/Suma/issues/17

But I'm not sure I understand what the format for the `timestamp` values should be, as well as the `startTime` and `endTime`. Could someone elaborate on this?

**Comment by kbeswick** [comment]
The timestamp values are in unix time  (https://en.wikipedia.org/wiki/Unix_time) . Most languages have methods to convert to this format. If you need any help with this conversion with the specific language or tool you are using to construct the JSON, let me know!
