### ISSUE TITLE
Incorrect Times

### ISSUE THREAD

**Issue by idean93** [suma-project/Suma#89]
The wrong times are being recorded in the database.

I have set the php.ini file and other apps on the same server are showing the correct time.  However, SUMA is still recording the wrong times.  It is also recording those wrong times in the log file.  When I take the timestamp from that log file and throw it into a date() php function in another app, it shows the correct time.

How is the timestamp sent to the database and how is it converted to a date/time?

Thanks.

EDIT: So it appears that the person who installed SUMA for my org made a huge mess of it and I wasn't getting the php.ini file in the correct location.  I still do not know the correct location as there are multiple copies of everything all over the place.  However I did carpet bomb my suma folder with the php.ini file and eventually got in the correct location, although like I said I still don't know what that location is as placing in the main SUMA directory did not work initially, hence the post awhile back.
If we update to 3.0 I believe we will do clean install to fix the mess my predecessors made and then I should be able to provide a better answer on the correct location of the .ini file.

**Comment by itsalljustaride** [comment]
I'm having the same issue. Trying to troubleshoot this via php.ini has no effect on the time as its being stored in the db or display via analysis. Other scripts show correct time/date.

**Comment by rtwilson** [comment]
Having the same issue. set in php.ini, server using local time, MySQL outputting local time and using system time. Anyone have any luck? Is this coming over from websql somehow?

**Comment by rtwilson** [comment]
@idean93 Would you be able to provide a list of which dirs you have php.ini? Unless it's truly in every single one. :) If i can pinpoint it, i'll happily update this issue.

**Comment by bretdavidson** [comment]
@idean93 @itsalljustaride @rtwilson Were you able to resolve the configuration issues with the timezone? I'm going to close this issue but please reopen if necessary. Thanks.

**Comment by IanDeanOUHSC** [comment]
The php.ini file needs to go in the /YOUR_WEB_DIR/sumaserver folder.
